title: Ben Casselman
description: Chief Economics Correspondent at The New York Times
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme

# Personal Info
email: ben.casselman@nytimes.com
linkedin_username: bencasselman
twitter_username: bencasselman
github_username: BenCasselman
